import { defineConfig } from "orval";

const doNotEditBanner = `/**
 * DO NOT EDIT MANUALLY
 *
 * Generated by Orval from FastAPI OpenAPI.
 * Regenerate with: npm run api:generate
 */
`;

export default defineConfig({
    api: {
        input: {
            target: "./openapi/openapi.json",
        },
        output: {
            mode: "tags-split",
            target: "./src/generated/endpoints",
            schemas: "./src/generated/models",
            client: "react-query",
            httpClient: "fetch",
            clean: true,
            prettier: false,
            override: {
                mutator: {
                    path: "./src/api/orvalMutator.ts",
                    name: "customFetch",
                },
                fetch: {
                    includeHttpResponseReturnType: false,
                },
                header: () => doNotEditBanner,
                query: {
                    useQuery: true,
                    useMutation: true,
                    signal: true,
                },
            },
        },
    },
    apiZod: {
        input: {
            target: "./openapi/openapi.json",
        },
        output: {
            mode: "tags-split",
            client: "zod",
            target: "./src/generated/zod",
            fileExtension: ".zod.ts",
            clean: true,
            prettier: false,
            override: {
                header: () => doNotEditBanner,
            },
        },
    },
});
